mysql:
  image: 'mysql:latest'
  volumes:
    - ./docker/dbdata:/var/lib/mysql
  ports:
    - '3306:3306'
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 2eed074d
    MYSQL_DATABASE: heroku_2d97ff46f0227d4